name: "Setup Environment"

description: "Installs build environment dependencies"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/cache@main
      with:
        path: |
          ~/.npm
          ~/.pnpm-store
          ./client/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
